apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{containerName}}
  namespace: did
  labels:
    app: {{containerName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{containerName}}
  template:
    metadata:
      labels:
        app: {{containerName}}
    spec:
      containers:
      - name: {{containerName}}
        image: {{containerTag}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{containerPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{containerName}}
  namespace: did
spec:
  type: NodePort
  selector:
    app: {{containerName}}
  ports:
    - protocol: TCP
      port: {{containerPort}}
      targetPort: {{containerPort}}
