apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-resolver-web
  namespace: did
  labels:
    app: uni-resolver
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uni-resolver-web
  template:
    metadata:
      labels:
        app: uni-resolver-web
        fargate: "true"
    spec:
      containers:
        - name: uni-resolver-web
          # Use the identity.com Docker image for the Universal Resolver Web
          # so that we can control the did methods supported - specifically add preview methods like "did:icp"
          # not yet supported in the upstream.
          # If we do not have any unofficial ones, we can and should use the upstream image instead
          image: identitydotcom/uni-resolver-web
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/1.0/methods"
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10 # set high to avoid unnecessary pod restarts
---
apiVersion: v1
kind: Service
metadata:
  name: uni-resolver-web
  namespace: did
spec:
  type: NodePort
  selector:
    app: uni-resolver-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
