apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-resolver-frontend
  namespace: did
  labels:
    app: uni-resolver
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uni-resolver-frontend
  template:
    metadata:
      labels:
        app: uni-resolver-frontend
        fargate: "true"
    spec:
      containers:
        - name: uni-resolver-frontend
          image: universalresolver/universal-resolver-frontend:0.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: uni-resolver-frontend
                  key: backend_url
---
apiVersion: v1
kind: Service
metadata:
  name: uni-resolver-frontend
  namespace: did
spec:
  type: NodePort
  selector:
    app: uni-resolver-frontend
  ports:
    - protocol: TCP
      port: 7081
      targetPort: 80
