name: Driver health check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run smoke tests
        uses: ./ci/smoke-tests
        with:
          host: https://dev.uniresolver.io
          out_folder: /github/workspace/driver-status-reports
          keep_result: true