name: AWS Kubernetes deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment ( dev / prod )'
        required: true
        default: 'dev'

env:
  IMAGE_NAME: universalresolver/uni-resolver-web
  PATH_TO_DOCKERFILE: uni-resolver-web/docker/Dockerfile
  BUILD_CONTEXT: $GITHUB_WORKSPACE

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
    - uses: actions/checkout@master

    - name: Deploy to AWS
      uses: ./ci/deploy-k8s-aws
      env:
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        RPC_URL_TESTNET: ${{env.RPC_URL_TESTNET}}
        RPC_CERT_TESTNET: ${{env.RPC_CERT_TESTNET}}
    - name: Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }} # required
      if: failure() # Send message only on failure
